// ﻿﻿Copyright (c) Code Impressions, LLC. All Rights Reserved.
//  
//  Licensed under the Apache License, Version 2.0 (the "License")
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//      http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

using System;
using System.Collections.Generic;
using Transmitly.Channel.Configuration.Email;
using Transmitly.ChannelProvider.SendGrid.Configuration;

namespace Transmitly
{
    /// <summary>
    /// The properties availble to a SendGrid Delivery Report.
    ///<para>
    /// Source: <seealso href="https://www.twilio.com/docs/sendgrid/for-developers/tracking-events/event"/> 
    /// </para>
    /// </summary>
    public interface IEmailExtendedDeliveryReportProperties
    {
        /// <summary>
        /// Adapts the channel configuration to an extend properties bag.
        /// </summary>
        /// <param name="email"></param>
        /// <returns></returns>
        IEmailExtendedChannelProperties Adapt(IEmailChannelConfiguration email);
        /// <summary>
        /// Advanced Subscription Management Group Id.
        /// </summary>
        int? AsmGroupId { get; set; }
        /// <summary>
        /// Twilio SendGrid conveniently buckets SMTP failure messages into classifications by mapping each unique 
        /// response to one of seven groups: Invalid Address, Technical, Content, Reputation, 
        /// Frequency/Volume, Mailbox Unavailable, or Unclassified. 
        /// See our 
        /// <a href="https://www.twilio.com/docs/sendgrid/ui/analytics-and-reporting/bounce-and-block-classifications">Bounce Classifications documentation</a>
        /// to understand each classification
        /// </summary>
        string? BounceClassification { get; set; }
        /// <summary>
        /// <seealso href="https://www.twilio.com/docs/sendgrid/glossary/categories">Categories</seealso>
        /// are custom tags that you set for the purpose of organizing your emails. 
        /// </summary>
        IReadOnlyCollection<string>? Categories { get; set; }
        /// <summary>
        /// Domain
        /// </summary>
        string? Domain { get; set; }
        /// <summary>
        /// The email address of the recipient.
        /// </summary>
        string? Email { get; set; }
        /// <summary>
        /// The event type. 
		/// Possible values: 
        ///     processed,
        ///     dropped,
        ///     delivered,
        ///     deferred,
        ///     bounce,
        ///     open,
        ///     click,
        ///     spam report,
        ///     unsubscribe,
        ///     group,
        ///     unsubscribe,
        ///     group resubscribe
        /// </summary>
        string? Event { get; set; }
        /// <summary>
        /// A unique ID to this event that you can use for deduplication purposes. 
        /// These IDs are up to 100 characters long and are URL safe
        /// </summary>
        string? EventId { get; set; }
        /// <summary>
        /// From address.
        /// </summary>
        string? From { get; set; }
        /// <summary>
        /// A new Boolean field that indicates whether or not an open event has been generated by 
        /// Apple Mail Privacy Protection (MPP). When this field is set to true, it means that 
        /// SendGrid has received signals indicating that a recipient with MPP enabled has triggered an open event. 
        /// When this field is false, it indicates that the event was triggered by a conventional open. 
        /// This field was added as a response to the anonymization of some open event tracking caused 
        /// by 
        /// <a href="https://sendgrid.com/blog/apple-mail-privacy-protection">Apple Mail Privacy Protection</a>.
        /// </summary>
        bool? MachineOpen { get; set; }
        /// <summary>
        /// A unique, internal SendGrid ID for the message. The first half of this ID is pulled from the smtp-id. 
        /// The message ID will be included in most cases. In the event of an 
        /// <a href="https://www.twilio.com/docs/sendgrid/ui/sending-email/bounces#asynchronous-bounces">asynchronous bounce</a>,
        /// the message ID will not be available. An asynchronous bounce occurs when a message is first accepted by the receiving 
        /// mail server and then bounced at a later time. When this happens, there is less information available about the bounce.
        /// </summary>
        string? MessageId { get; set; }
        /// <summary>
        /// Any sort of error response returned by the receiving server that describes the reason this event type was triggered.
        /// </summary>
        string? Reason { get; set; }
        /// <summary>
        /// The full text of the HTTP response error returned from the receiving server.
        /// </summary>
        string? Response { get; set; }
        /// <summary>
        /// A unique ID attached to the message by the originating system.
        /// </summary>
        string? SmtpId { get; set; }
        /// <summary>
        /// Status code string. Corresponds to HTTP status code - for example, 
        /// a JSON response of 5.0.0 is the same as a 500 error response.
        /// </summary>
        string? Status { get; set; }
        /// <summary>
        /// The exact time the associated event occurred.
        /// </summary>
        DateTimeOffset? Timestamp { get; set; }
        /// <summary>
        /// <list type="bullet">
        /// <item>Bounce event
        ///     <description>indicates whether the bounce event was a hard bounce (type=bounce) or block (type=blocked).</description>
        /// </item>
        /// <item>
        /// Account status change event
        ///     <description>The status a user has been switched to for compliance reasons.</description>
        /// </item>
        /// </list>
        /// </summary>
        string? Type { get; set; }
        /// <summary>
        /// The URL where the event originates. For click events, this is the URL clicked on by the recipient.
        /// </summary>
        string? Url { get; set; }
        /// <summary>
        /// The user agent responsible for the event. This is usually a web browser. 
        /// </summary>
        /// <example>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.95 Safari/537.36</example>
        string? UserAgent { get; set; }
        /// <summary>
        /// The number of times SendGrid has attempted to deliver this message.
        /// </summary>
        int? Attempt { get; set; }
        /// <summary>
        /// The IP address used to send the email. For <c>open</c> and <c>click</c> events, it is the IP address of the recipient 
        /// who engaged with the email. 
        /// <para>The IP address will not be available in the response json for certain events such as <c>deferral</c> and <c>bounce</c>.</para>
        /// </summary>
        string? Ip { get; set; }

    }
}